Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,9 +32,11 @@ jobs:
         tar zxf jena.tar.gz && \
         rm jena.tar.gz*
     - name: generate other syntaxes for ontologies 
-      run: for onto in *.ttl; do echo "Generate for ${onto%.*}"; for syntax in "RDF/XML rdf" "N-TRIPLE nt" "N3 n3" "JSON-LD jsonld"; do set -- $syntax; echo " - ${onto%.*}.$2"; apache-jena-3.14.0/bin/riot --output=$1 ${onto%.*}.ttl >> ${onto%.*}.$2 || echo "RIOT error" >> ${onto%.*}.$2 ; done; done
+      run: for onto in *.ttl; do echo "Generate for ${onto%.*}"; for syntax in "RDF/XML rdf" "N-TRIPLE nt" "N3 n3" "JSON-LD jsonld"; do set -- $syntax; echo " - ${onto%.*}.$2"; apache-jena-3.14.0/bin/riot --output=$1 ${onto%.*}.ttl >> ${onto%.*}.$2 || echo "RIOT error" > ${onto%.*}.$2 ; done; done
     - name: delete jena
       run: rm -r apache-jena-$JENA_VERSION
+    - name: delete hidden files
+      run: rm -rf .* || true
     - name: GitHub Pages Deploy
       uses: maxheld83/ghpages@v0.2.1
       env:
